'''
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
'''
def findTheDifference(self, s: str, t: str) -> str:
    merged = s + t
    ans = 0 
    for i in merged:
        ans = ans ^ ord(i)

    return chr(ans)